### ISSUE TITLE
✔ App Roadmap

### ISSUE THREAD

**Issue by cristianprochnow** [cristianprochnow/move-it#3]
### MongoDB setup

- [x] Create MongoDB connection
- [x] Create initial state of signup function
- [x] Implement MongoBD interaction

### Alerts about operations

- [x] Add pop-up alert to advert about GitHub username storage at database
- [x] Add stack alert about success or errors of operations
- [x] Update submit button from `index.tsx` with spinning loading
- [x] Add `redirectToApp()` method into submit function of homepage

### Interactions with system

- [x] Add `logout` function to clear all the cookies into `logout` button within app page
- [x] Transport business rule from `GitHubUsernameInputGroup` component to `index.tsx` page

### Data manipulation

- [x] Create context about user data
- [x] Update collection of MongoDB
- [x] Update `levelup` function to insert game data into the database
- [x] Update `completeChallenge` function to insert game data into the database
- [x] Add verifications to ensure that the same user do not sign up twice or more
- [x] Define logic to log in or sign up automatically
- [x] Add user context into `app.tsx` page
- [x] Integrate user context with cookies
- [x] List ranking of users at `/ranking`

### API Routing

- [x] Refactor `signup` route
- [x] Update `signup` function with additional data to insert into database
- [x] Create route for list user information
- [x] Create route for update the saved `level`
- [x] Create route for update saved `completedChallenges`
- [x] Create route for update saved `currentExperience`
- [x] ~Create route to update user automatically~

### Documentation

- [x] Update demonstration GIF
